name: Issue

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: macos-latest
    steps:
      - name: create comment on issue
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.MY_GITHUB_ACTION_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ðŸ‘‹ Thanks for reporting!'
            })

      - name: add label on issue
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.MY_GITHUB_ACTION_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Merge Needed']
            })
